version: "3"

services:
    server:
        image: rescuehub/server:latest
        expose:
          - 8080
        depends_on:
          - postgres
        environment:
          - FB_CLIENT_ID=${FB_CLIENT_ID}
          - FB_CLIENT_SECRET=${FB_CLIENT_SECRET}

    postgres:
        hostname: postgres
        image: rescuehub/postgres:latest
        expose:
          - 5432

    ui:
        image: rescuehub/ui:latest
        depends_on:
          - server
        ports:
          - 9000:9000
        volumes:
          - ${PWD}/certs:/certs



