spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/rescuehub
    username: rescuehub-user
    password: kittens@123

  jpa:
    hibernate:
      ddl-auto: update
      use-new-id-generator-mappings: false
    properties:
      hibernate.jdbc.lob.non_contextual_creation: true
  database-platform: org.hibernate.dialect.PostgreSQLDialect

  social:
    facebook:
      appId: ${FB_CLIENT_ID}
      appSecret: ${FB_CLIENT_SECRET}
    auto-connection-views: false

  security:
    basic:
      enabled: false
  #   oauth2:
  #     client:
  #       provider:
  #         facebook:
  #           user-info-uri: https://graph.facebook.com/me?fields=email,name,verified
  #           authorization-uri: https://www.facebook.com/v3.0/dialog/oauth
  #           token-uri: https://graph.facebook.com/v3.0/oauth/access_token
  #       registration:
  #         # google:
  #         #   client-id: xxxxx
  #         #   client-secret: xxxx
  #         facebook:
  #           client-id: ${FB_CLIENT_ID}
  #           client-secret: ${FB_CLIENT_SECRET}
  #           # redirect-uri-template: "{baseUrl}/social-login-success"
  #           redirect-uri-template: "{baseUrl}/oauth2/callback/{registrationId}"
  #           # This bit is important!
  #           authorization-grant-type: implicit
  #           scope:
  #             - email
  #             - public_profile

  # JSON serialization settings
  jackson:
    default-property-inclusion: NON_NULL

    serialization:
      write-null-map-values: false

    deserialization:
      accept-single-value-as-array: true

  devtools:
    # Comment this if you want the app to restart
    # when source code changes
    restart.enabled: false
    livereload.enabled: false

server:
  servlet.session.persistent: false
  port: 8080
  use-forward-headers: true

logging:
  level:
    root: INFO
    com.naturalprogrammer: DEBUG
    com.rescuehub: DEBUG
    org.springframework.security.oauth2.client: DEBUG


app:
  base-url: https://localhost:9000/api
  auth:
    jwt:
      secret: T8f8tK4cv7S8aGhmlXBEIJPUp53uxO6FRcyV132h2DY0Jf5Va6TfYqbIUjIFx2aL
      expiration-millis: 864000000 # 10 days
      short-lived-millis: 120000   # two minutes
  oauth2:
    authorized-redirect-uris:
      - "{baseUrl}/oauth2/redirect"


